# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('course', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=6)),
                ('starosta_phone_number', models.CharField(max_length=12)),
                ('curator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeWinningPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('educational_form', models.CharField(max_length=8)),
                ('average_score', models.PositiveSmallIntegerField(default=0)),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup')),
                ('student_exam', models.ManyToManyField(through='academic_groups.ExamResult', to='academic_groups.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='prize_winning_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.PrizeWinningPlace'),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='student_event',
            field=models.ManyToManyField(to='academic_groups.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EventArea'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EventLevel'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='exams',
            field=models.ManyToManyField(to='academic_groups.Exam'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='starosta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
