# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('course', models.PositiveSmallIntegerField()),
                ('academic_group_name', models.CharField(max_length=6)),
                ('starosta', models.CharField(max_length=50)),
                ('curator', models.CharField(max_length=50)),
                ('student_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_area', models.CharField(choices=[('kmd', 'Культурно-массовая деятельность'), ('sd', 'Спортивная деятельность'), ('nd', 'Научная деятельность'), ('od', 'Общественная деятельность')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('educational_form', models.CharField(choices=[('b', 'бюджет'), ('k', 'контракт')], max_length=8)),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
        ),
    ]
