# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_level',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='event',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event_area',
            field=models.CharField(choices=[('n', 'Научная'), ('k', 'Культурно-массовая'), ('s', 'Спортивная'), ('o', 'Общественная')], default='n', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event_level',
            field=models.CharField(choices=[('ml', 'Международный'), ('rl', 'Всероссийский'), ('rl', 'Региональный'), ('gl', 'Городской'), ('ul', 'Университетский')], default='ul', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='exams',
            field=models.ManyToManyField(blank=True, to='academic_groups.Exam'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='prize_winning_place',
            field=models.CharField(choices=[('0', 'участие'), ('1', '1 место'), ('2', '2 место'), ('3', '3 место')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventArea',
        ),
        migrations.DeleteModel(
            name='EventLevel',
        ),
        migrations.DeleteModel(
            name='PrizeWinningPlace',
        ),
    ]
