# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='starosta_email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='starosta_phone_number',
            field=models.CharField(default=' ', max_length=12),
            preserve_default=False,
        ),
    ]
