# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0002_auto_20170710_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_level',
            field=models.CharField(choices=[('ml', 'Международный уровень'), ('rl', 'Всероссийский уровень'), ('rl', 'Региональный уровень'), ('gl', 'Городской уровень'), ('ul', 'Университетский уровень')], default=' ', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='prize_wining_place',
            field=models.CharField(choices=[('1', '1 место'), ('2', '2 место'), ('3', '3 место'), ('4', 'участие')], default=' ', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_area',
            field=models.CharField(choices=[('kmd', 'Культурно-массовая деятельность'), ('sd', 'Спортивная деятельность'), ('nd', 'Научная деятельность'), ('od', 'Общественная деятельность')], max_length=31),
        ),
    ]
