# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0003_auto_20170716_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='academic_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup'),
            preserve_default=False,
        ),
    ]
