# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0003_auto_20170710_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeWinningPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='academicgroup',
            old_name='academic_group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='prize_wining_place',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='starosta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EventArea'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EventLevel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EducationalForm'),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='prize_winning_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.PrizeWinningPlace'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.EventGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='prize_winning_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.PrizeWinningPlace'),
            preserve_default=False,
        ),
    ]
