# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0004_auto_20170711_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='curator',
        ),
        migrations.AddField(
            model_name='curator',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup'),
        ),
    ]
