# Generated by Django 2.2.4 on 2019-08-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0006_auto_20170717_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='average_score',
        ),
    ]
