# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0006_auto_20170711_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='starosta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
        ),
    ]
