# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0007_auto_20170711_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_event_group',
            field=models.ManyToManyField(to='academic_groups.EventGroup'),
        ),
    ]
