# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0008_student_student_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_exam',
            field=models.ManyToManyField(through='academic_groups.ExamResult', to='academic_groups.Exam'),
        ),
    ]
