# Generated by Django 2.2.4 on 2019-08-17 06:55

import academic_groups.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0010_student_educational_form_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'verbose_name': 'Академическая группа', 'verbose_name_plural': 'Академические группы'},
        ),
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'verbose_name': 'Группа мероприятия', 'verbose_name_plural': 'Группы мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Результат экзамена', 'verbose_name_plural': 'Результаты экзаменов'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='course',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='curator',
            field=models.CharField(max_length=50, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='exams',
            field=models.ManyToManyField(blank=True, to='academic_groups.Exam', verbose_name='Экзамены'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='institute',
            field=models.CharField(max_length=200, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(max_length=6, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='starosta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Староста'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='starosta_phone_number',
            field=models.CharField(max_length=12, validators=[academic_groups.models.validate_telephone_number], verbose_name='Номер старосты'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup', verbose_name='Академическая группа'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='event_area',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Научная'), (1, 'Культурная'), (2, 'Спортивная'), (4, 'Общественная')], verbose_name='Область мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='event_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Международный'), (1, 'Всероссийский'), (2, 'Региональный'), (3, 'Городской'), (4, 'Университетский')], verbose_name='Уровень мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='event_name',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='prize_winning_place',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 место'), (2, '2 место'), (3, '3 место'), (0, 'участие')], verbose_name='Призовое место'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='student_event',
            field=models.ManyToManyField(blank=True, to='academic_groups.Student', verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup', verbose_name='Академическая группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_form',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Бюджет'), (1, 'Контракт')], verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
