# Generated by Django 2.2.4 on 2019-08-17 06:58

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Event = apps.get_model('academic_groups', 'Event')
    EventGroup = apps.get_model('academic_groups', 'EventGroup')
    for event_group in EventGroup.objects.all():
        event = Event(name=event_group.event_name, area=event_group.event_area, level=event_group.event_level)
        event.save()
        event_group.event = event
        event_group.save()


def backward(apps, schema_editor):
    EventGroup = apps.get_model('academic_groups', 'EventGroup')
    for event_group in EventGroup.objects.all():
        event_group.event_name = event_group.event.name
        event_group.event_area = event_group.event.area
        event_group.event_level = event_group.event.level
        event_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('academic_groups', '0011_auto_20190817_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('area', models.PositiveSmallIntegerField(
                    choices=[(0, 'Научная'), (1, 'Культурная'), (2, 'Спортивная'), (4, 'Общественная')],
                    verbose_name='Область мероприятия')),
                ('level', models.PositiveSmallIntegerField(
                    choices=[(0, 'Международный'), (1, 'Всероссийский'), (2, 'Региональный'), (3, 'Городской'),
                             (4, 'Университетский')], verbose_name='Уровень мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.RenameField(
            model_name='eventgroup',
            old_name='student_event',
            new_name='students',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Event',
                                    verbose_name='Мероприятие'),
            preserve_default=False,
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='eventgroup',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='event_area'
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='event_level'
        )
    ]
