# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0011_remove_event_prize_winning_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student_event',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='student_event',
            field=models.ManyToManyField(to='academic_groups.Student'),
        ),
    ]
