# Generated by Django 2.2.4 on 2019-08-19 07:49

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    AcademicGroup = apps.get_model('academic_groups', 'AcademicGroup')
    AcademicGroupExam = apps.get_model('academic_groups', 'AcademicGroupExam')
    for academic_group in AcademicGroup.objects.all():
        for exam in academic_group.exams.all():
            AcademicGroupExam.objects.create(academic_group=academic_group, exam=exam)


def backward(apps, schema_editor):
    AcademicGroupExam = apps.get_model('academic_groups', 'AcademicGroupExam')
    for academic_group_exam in AcademicGroupExam.objects.all():
        academic_group_exam.academic_group.exams.add(academic_group_exam.exam)


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0012_auto_20190817_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroupExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.AcademicGroup', verbose_name='Академическая группа')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Exam', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Экзамен академической группы',
                'verbose_name_plural': 'Экзамены академичских групп',
            },
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='AcademicGroup',
            name='exams'
        )
    ]
