# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0012_auto_20170711_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_group',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_groups.Event'),
            preserve_default=False,
        ),
    ]
