# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0012_auto_20170711_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='starosta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
