# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0015_auto_20170713_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='exams',
            field=models.ManyToManyField(to='academic_groups.Exam'),
        ),
    ]
