# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0017_examtoacademicgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtoacademicgroup',
            name='academic_group',
        ),
        migrations.RemoveField(
            model_name='examtoacademicgroup',
            name='exam',
        ),
        migrations.DeleteModel(
            name='ExamToAcademicGroup',
        ),
    ]
