# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0018_auto_20170713_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='student_count',
        ),
        migrations.AddField(
            model_name='student',
            name='average_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='course',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
