# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_groups', '0019_auto_20170714_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='curator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_form',
            field=models.CharField(max_length=8),
        ),
        migrations.DeleteModel(
            name='Curator',
        ),
        migrations.DeleteModel(
            name='EducationalForm',
        ),
    ]
